// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC31fkIM12Ej9OFtOOLWNkHjIRD7DTwFz8',
    appId: '1:455532501676:web:e7c08541d9708b46211d09',
    messagingSenderId: '455532501676',
    projectId: 'test1-711a2',
    authDomain: 'test1-711a2.firebaseapp.com',
    storageBucket: 'test1-711a2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdcJjBBM3WITcVDRTP5uxKk4qYVnhjEfw',
    appId: '1:455532501676:android:3e2ea4e9786ede95211d09',
    messagingSenderId: '455532501676',
    projectId: 'test1-711a2',
    storageBucket: 'test1-711a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSgdoxkpgwA_9Urni4cw2NyGfEuEY6aGo',
    appId: '1:455532501676:ios:6361eaa6c688dd9c211d09',
    messagingSenderId: '455532501676',
    projectId: 'test1-711a2',
    storageBucket: 'test1-711a2.appspot.com',
    iosClientId: '455532501676-ifjnn8ltqhbulqan4krbc45oafnqdo7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.tradingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSgdoxkpgwA_9Urni4cw2NyGfEuEY6aGo',
    appId: '1:455532501676:ios:6361eaa6c688dd9c211d09',
    messagingSenderId: '455532501676',
    projectId: 'test1-711a2',
    storageBucket: 'test1-711a2.appspot.com',
    iosClientId: '455532501676-ifjnn8ltqhbulqan4krbc45oafnqdo7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.tradingApp',
  );
}
